### ISSUE TITLE
Error on YOUR PROFILE DC

### ISSUE THREAD

**Issue by DaiJunyan** [PHME-Datachallenge/Data-Challenge-2022#10]
There's an error when I try to edit my personal information on my profile (Edit first name and last name)
![image](https://user-images.githubusercontent.com/28862999/166298108-64c1c006-a50a-4d46-8d65-109523fc67c8.png)

**Comment by dgiordan88** [comment]
Dear DaiJuyan,
This problem is related to the phme website. Please contact the Website Chair for handling it.

Best,

Danilo
