### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by MeritxellGomez** [PHME-Datachallenge/Data-Challenge-2022#13]
Dear organizers, 

We had understood that in model 3 we could use OperatorLabel as an input to predict RepairLabel. That can be read in the header of the function classification_3 of the solution.ipynb. However, in data_challenge_evaluation_metric.pdf we can see in red AOILabel ONLY when you explain the structure of the AOI validation set. Can you please clarify that?

Best regards, 
Meritxell

**Comment by dgiordan88** [comment]
Dear Meritxell,
We have updated the slides to make the evaluation description consistent. 
You can also find the details of the score function.

Best,

Danilo
