### ISSUE TITLE
4 training files

### ISSUE THREAD

**Issue by Bulbille** [PHME-Datachallenge/Data-Challenge-2022#14]
Hi 
Are the 4 SPI files are splitted because it's too heavy to be on gitlab ? For my training, should I recompose everything into one big file ?

Thanks, 
pgersberg

**Comment by dgiordan88** [comment]
Dear pgersberg,

That's correct. The split is only instrumental due to the file size. Each file represents part of the SPI training dataset.  

Best,

Danilo Giordano
