### ISSUE TITLE
Several question about paper and test set

### ISSUE THREAD

**Issue by kckenni** [PHME-Datachallenge/Data-Challenge-2022#15]
Dear Organizer,
I have several questions about the challenge.
1.I found out that the due date of the short paper describing team solution is June 12. So does this mean that it is fine to submit the short paper after May 27(Competition closed date)
2. When will the separate test set to calculate the score be opened?
3. I have a question about the peer-reviewed conference paper which winning team subimits. Will the paper be reviewed by PHM 2022 conference or other groups(such as professor or experts)?

Best regards,
gunwoo

**Comment by dgiordan88** [comment]
Dear gunwoo,
1. The short paper has to be submitted along with the jupyter notebook - please refer to the https://github.com/PHME-Datachallenge/Data-Challenge-2022/blob/main/data_challenge_evaluation_process.pdf for all information about submission format

2. We are working on this possibility, as soon as we make it available we will post an update on the Github repository.

3. The papers of the winning teams will go under review of the data challenge committee only. The committee will provide feedback on how to improve it for the camera ready.

Best

Danilo Giordano

**Comment by kckenni** [comment]
Dear Organizer,
Thank you.
Are there required components or required format for the short paper?
