### ISSUE TITLE
How do we submit our final results?

### ISSUE THREAD

**Issue by da-mape** [PHME-Datachallenge/Data-Challenge-2022#17]
Dear organizers,

I don't see any option for uploading files to the DC profile page (https://phm-europe.org/your-profile-dc).
How do you expect the submission to reach you? As a zip file via mail? Or is it enough to upload the final files (including the pdf of the paper) onto the jupyter server?

Best regards,
Max-Peter

**Comment by dgiordan88** [comment]
Dear Max-Peter,
The paper along with the Jupyter notebook and models have to be uploaded as a zip file on the DC profile page. 
We are working on the submission portal to make it available soon.

Best,

Danilo
