### ISSUE TITLE
Post-challenge data

### ISSUE THREAD

**Issue by Bulbille** [PHME-Datachallenge/Data-Challenge-2022#19]
Hello, 
With only 1 week of work, I won't be able to have good results. 
Will you give us, after friday, the test files, or will the jupyterlab will keep working for some time, so we can get a score for ourselves beyond the deadline ?

Thanks

**Comment by dgiordan88** [comment]
Dear Bulbille,
FYI: we are planning to grant an extension. More information will come soon.
The test dataset will not be released until future indication - typically after the conference runs.  
The jupyterlab environment will be available up middle/end of July - afterwards, all accounts will be removed. 

Best,

Danilo
