### ISSUE TITLE
How do you rank teams based on three f1 scores?

### ISSUE THREAD

**Issue by DaiJunyan** [PHME-Datachallenge/Data-Challenge-2022#2]
According to the "solution.ipynb", three f1 scores will be calculated in the end, one for each task. How do you rank teams based on the three f1 scores?

**Comment by PHME-Datachallenge** [comment]
Dear DaiJunyan,
Currently this is a basic template and does not contain the final scoring function yet.
We will update the scoring information soon. 
Thanks for your interest in the challenge. 

Best,
Danilo Giordano & Martino Trevisan
