### ISSUE TITLE
When the leadearboard wrap the code and evaluate?

### ISSUE THREAD

**Issue by K0BigYang** [PHME-Datachallenge/Data-Challenge-2022#22]
Dear Organizer,

Like the title, it seems doesn't update my score which user name is kyang.
If we want to update the codes, what is the deadline of time in each day?

**Comment by dgiordan88** [comment]
Dear K0BigYang,
The score is computed every night, and the results are published in the morning.
The score is computed independently every night so it does not take into account previous performance.  

Best,

Danilo Giordano
