### ISSUE TITLE
Leader board update before the deadline

### ISSUE THREAD

**Issue by DaiJunyan** [PHME-Datachallenge/Data-Challenge-2022#27]
Dear Organizer,

Will you update the leaderboard on the last day (June 8th) before the deadline (June 8th at 11:59:59 PM GMT)? If so, will you consider the score updated on June 8th as the final score? Or will you recompute our code after the deadline so that we still have a chance to modify our code when we see the scores on the last day?

Best regards,
Junyan

**Comment by DaiJunyan** [comment]
Also, will the final score be computed using the current test set or another validation set?

**Comment by marty90** [comment]
the current test set
