### ISSUE TITLE
Inquiry about the TEST.py code

### ISSUE THREAD

**Issue by kckenni** [PHME-Datachallenge/Data-Challenge-2022#28]
Dear Organizer,

I have one question about TEST.py code. 
results_3 = classification_3(SPI, AOI[["PanelID","FigureID","MachineID","ComponentID","PinNumber","AOILabel","RepairLabel"]])
I think the above code should change to
results_3 = classification_3(SPI, AOI[["PanelID","FigureID","MachineID","ComponentID","PinNumber","AOILabel","OperatorLabel"]])
So 'RepairLabel' to 'OperatorLabel'
I would appreciate if you tell me i am thinking wrong.
Best regards,
gunwoo

**Comment by marty90** [comment]
Yes, it was a mistake on the previous versions.
The current code is:
```python
results_3 = classification_3(SPI, AOI[["PanelID","FigureID","MachineID","ComponentID","PinNumber","AOILabel","OperatorLabel"]])
```
