### ISSUE TITLE
More unique {PaneiID, FigureID} in AOI than SPI

### ISSUE THREAD

**Issue by DaiJunyan** [PHME-Datachallenge/Data-Challenge-2022#3]
In AOI data, there are some unique {PanelID, FigureID} records that do not exist in SPI data. This means that the number of unique IDs {PanelID, FigureID, ComponentID} in the AOI dataset is larger than that in the SPI dataset. This is obviously unreasonable.
One example is PanelID=26919053400520102844, FigureID={4, 5, 6, 8}.

**Comment by dgiordan88** [comment]
Dear DaiJunyan,
Thanks for noticing. These are the only cases where AOI data reports more Figures than SPI. 
This is due to the nature of the data: being collected from a real scenario may contain a few missing records. 
You can ignore AOI labels. 

Best,
Danilo Giordano & Martino Trevisan

**Comment by DaiJunyan** [comment]
Understood. Thanks!
