### ISSUE TITLE
No RepairLabel has a "Repaired" label

### ISSUE THREAD

**Issue by DaiJunyan** [PHME-Datachallenge/Data-Challenge-2022#4]
It is mentioned on the website that the RepairLabel includes a possible label "Repaired", but the actual dataset we have received does not have this value. I wonder if there is no such "Repaired" label, or it is caused by the incomplete data?

**Comment by dgiordan88** [comment]
Dear DaiJunyan,
Thanks for noticing. This label is not present in the dataset (nor in the training nor in the test dataset). 
We will update the data challenge text description accordingly.

Best,
Danilo Giordano & Martino Trevisan

**Comment by DaiJunyan** [comment]
Got it. Thank you!
