### ISSUE TITLE
Need more description about some of the columns

### ISSUE THREAD

**Issue by mehrnazmrz** [PHME-Datachallenge/Data-Challenge-2022#7]
In the SPI data-set, we have "Result," which includes ten different data types. I don't understand precisely the meaning of this data. Does that mean anything rather than "Good" the solder has a problem? What is the difference when it starts with "E" and "W"?

Also, what is the exact definition of shape? the amount is sometimes negative and sometimes zero! Could you please give some more information about this column?

Thank you,
Mehrnaz

**Comment by dgiordan88** [comment]
Dear Mehrnaz,
A new file called "SPI-ColumnDescription.txt" is now available. It reports the meaning of each column of the SPI dataset. Regarding the Result no semantic information is available. 

Best,

Danilo

**Comment by mehrnazmrz** [comment]
Thank you so much.
